### PR TITLE
build: support python 3.13, drop python 3.8

### PR DESCRIPTION
**Pull request by tlambert03**
curious to see whether it fails.  

for some reason, I'm currently unable to build pymmcore with any version of python locally on my mac:

```python
* Building wheel...
No `packages` or `py_modules` configuration, performing automatic discovery.
`src-layout` detected -- analysing ./src
discovered packages -- ['pymmcore']
discovered py_modules -- []
running bdist_wheel
running build
running build_py
running build_ext
running build_clib
building 'MMDevice' library
creating build/temp.macosx-11.0-arm64-cpython-312/mmCoreAndDevices/MMDevice
clang++ -fno-strict-overflow -DNDEBUG -O2 -Wall -fPIC -O2 -isystem /Users/talley/miniforge3/envs/py312/include -arch arm64 -fPIC -O2 -isystem /Users/talley/miniforge3/envs/py312/include -arch arm64 -DMMDEVICE_CLIENT_BUILD -ImmCoreAndDevices/MMDevice -c mmCoreAndDevices/MMDevice/Debayer.cpp -o build/temp.macosx-11.0-arm64-cpython-312/mmCoreAndDevices/MMDevice/Debayer.o
In file included from mmCoreAndDevices/MMDevice/Debayer.cpp:26:
In file included from mmCoreAndDevices/MMDevice/Debayer.h:27:
In file included from mmCoreAndDevices/MMDevice/ImgBuffer.h:26:
mmCoreAndDevices/MMDevice/ImageMetadata.h:329:58: error: ISO C++17 does not allow dynamic exception specifications [-Wdynamic-exception-spec]
  329 |    MetadataSingleTag GetSingleTag(const char* key) const throw (MetadataKeyError)
      |                                                          ^~~~~~~~~~~~~~~~~~~~~~~~
mmCoreAndDevices/MMDevice/ImageMetadata.h:329:58: note: use 'noexcept(false)' instead
  329 |    MetadataSingleTag GetSingleTag(const char* key) const throw (MetadataKeyError)
      |                                                          ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                                          noexcept(false)
mmCoreAndDevices/MMDevice/ImageMetadata.h:336:56: error: ISO C++17 does not allow dynamic exception specifications [-Wdynamic-exception-spec]
  336 |    MetadataArrayTag GetArrayTag(const char* key) const throw (MetadataKeyError)
      |                                                        ^~~~~~~~~~~~~~~~~~~~~~~~
mmCoreAndDevices/MMDevice/ImageMetadata.h:336:56: note: use 'noexcept(false)' instead
  336 |    MetadataArrayTag GetArrayTag(const char* key) const throw (MetadataKeyError)
      |                                                        ^~~~~~~~~~~~~~~~~~~~~~~~
      |                                                        noexcept(false)
2 errors generated.
error: command '/opt/homebrew/opt/llvm/bin/clang++' failed with exit code 1

ERROR Backend subprocess exited when trying to invoke build_wheel
```

probably something on my end

### CODE REVIEW

**Comment by marktsuchida** [comment]
I think I have a fix for that. Let me see.

**Comment by marktsuchida** [comment]
Or so I thought, but it looks like setuptools is not applying the `CFLAGS` we specify any more, which is going to be a problem even if we work around the C++17 problem. Will continue to investigate.

**Comment by marktsuchida** [comment]
Broken since setuptools [v72.2.0](https://setuptools.pypa.io/en/latest/history.html#v72-2-0); builds with v72.1.0.

**Comment by tlambert03** [comment]
k, building now, including py3.13

**Comment by tlambert03** [comment]
want to drop py3.8 support, which is officially end of life in october?

**Comment by tlambert03** [comment]
> Broken since setuptools [v72.2.0](https://setuptools.pypa.io/en/latest/history.html#v72-2-0); builds with v72.1.0.

i guess this makes #109 more important :)

**Comment by tlambert03** [comment]
done
